version: "3"

services:
  postgres:
    image: docker.io/postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - postgres
      
  # pgAdmin:
  #   image: docker.io/dpage/pgadmin4
  #   container_name: pgAdmin
  #   env_file:
  #     - ./.env
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - postgres
      
volumes:
  progresDB:

networks:
  postgres:
    driver: bridge